<SelectableGrid>:
    rv: rv_id
    cols: 1
    rows: 1
    RecycleView:
        bar_width: self.width / 20
        bar_height: self.height / 15
        id: rv_id
        viewclass: 'RowLayout'
        size_hint: 1, 0.7
        SelectableRecycleBoxLayout:
            default_size: None, dp(75)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'


<GridWithTitles>:
    cols: 1
    rows: 2
    padding: 0, root.height * 0.1, 0, root.height * 0.2