#:kivy 2.1.0

<MoveAdditionFast>:
    speed_pve: speed_pve
    speed_pvp: speed_pvp
    energy_pve: energy_pve
    energy_pvp: energy_pvp
    Widget:
        GridLayout:
            width: root.width
            height: root.height
            padding: root.width * 0.05, root.height * 0.1, root.width * 0.05, root.height * 0.2
            spacing: root.width * 0.05, root.height * 0.1
            rows: 2
            cols: 2
            BoxLayout:
                orientation: 'vertical'
                Label:
                    text: "Скорость в PvE"
                TextInput:
                    id: speed_pve
            BoxLayout:
                orientation: 'vertical'
                Label:
                    text: "Скорость в PvP"
                TextInput:
                    id: speed_pvp
            BoxLayout:
                orientation: 'vertical'
                Label:
                    text: "Энергия в PvE"
                TextInput:
                    id: energy_pve
            BoxLayout:
                orientation: 'vertical'
                Label:
                    text: "Энергия в PvP"
                TextInput:
                    id: energy_pvp
        Button:
            center_y: 75
            center_x: root.width / 4
            font_size: 24
            size: 200, 75
            text: "Главное меню"
            on_release: root.to_main()
        Button:
            center_y: 75
            center_x: root.width / 2
            font_size: 24
            size: 200, 75
            text: "Назад"
            on_release: root.go_back()
        Button:
            center_y: 75
            center_x: root.width * 0.75
            font_size: 24
            size: 200, 75
            text: "Продолжить"
            on_release: root.proceed()


