#:kivy 2.1.0
<DataCollectorScreen>:
    Widget:
        Label:
            center_y: root.height - 75
            center_x: root.width / 2
            font_size: 32
            size: 200, 75
            text: "Обрабатывается покемон:"
        Label:
            id: current_pokemon
            center_y: root.height / 2
            center_x: root.width / 2
            font_size: 32
            size: 200, 75
            text: ''

