#:kivy 2.1.0

<SelectMoveRowLayout>:
    move_name: ''
    move_type: ''
    orientation: 'horizontal'
    Label:
        text: root.move_name
    Label:
        text: root.move_type


<MoveAdditionHead>
    cols: 2
    rows: 1
    size_hint_y: 0.1
    Label:
        text: 'Move name'
    Label:
        text: 'Move type'


<GoAddPokemonMoves>:
    moves_selectors: moves_selectors
    GridLayout:
        spacing: root.width * 0.05, 0
        id: moves_selectors
        rows: 1
        cols: 2